# This file was generated by GoReleaser. DO NOT EDIT.
class Helmreleaser < Formula
  desc "The easiest way to publish Helm charts"
  homepage "https://helmreleaser.com/"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/helmreleaser/helmreleaser/releases/v0.2.0/helmreleaser_0.2.0_darwin_amd64-0.2.0.tar.gz"
    sha256 "e2963e071bc48c01135c0e32ed19c9758cfabc9df493cbafbd219fece7001bb2"
  elsif OS.linux?
    url "http://github.com/helmreleaser/helmreleaser/releases/v0.2.0/helmreleaser_0.2.0_linux_amd64-0.2.0.tar.gz"
    sha256 "49d29cf92f552688ca3654ebce76d61a174c407479929766774f1711a8b57acf"
  end

  def install
    bin.install "helmreleaser"
  end
end
