# This file was generated by GoReleaser. DO NOT EDIT.
class Helmreleaser < Formula
  desc "The easiest way to publish Helm charts"
  homepage "https://helmreleaser.com/"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/helmreleaser/helmreleaser/releases/v0.2.0/helmreleaser_0.2.0_darwin_amd64-0.2.0.tar.gz"
    sha256 "bec79259abf70992598725406bdbf2ccbad38fd13eeaef52ce1bef456e6fa424"
  elsif OS.linux?
    url "http://github.com/helmreleaser/helmreleaser/releases/v0.2.0/helmreleaser_0.2.0_linux_amd64-0.2.0.tar.gz"
    sha256 "0e5a1fd6ba67dd538e7bb144a6ed7d46d17d307c20bd2051b871bbe20b5e1ebc"
  end

  def install
    bin.install "helmreleaser"
  end
end
